export const ERRORS = "ERRORS";
export const LOADING_USER = "LOADING_USER";
export const SET_CURRENT_USER = "SET_CURRENT_USER";

export const ADD_RTSP_URL = "ADD_RTSP_URL"
export const GET_RTSP_BY_USER_REQUEST = "GET_RTSP_BY_USER_REQUEST"
export const GET_RTSP_BY_USER_SUCCESS = "GET_RTSP_BY_USER_SUCCESS"
export const GET_RTSP_BY_USER_FAILURE = "GET_RTSP_BY_USER_FAILURE"

export const UPDATE_RTSP_SOCKET_DATA = "UPDATE_RTSP_SOCKET_DATA";
export const UPDATE_RTSP_SOCKET_DATA_FAILURE = "UPDATE_RTSP_SOCKET_DATA_FAILURE";
export const UPDATE_RTSP_SOCKET_DATA_SUCCESS = "UPDATE_RTSP_SOCKET_DATA_SUCCESS";